version: '3.8'

services:
  api:
    restart: always
    container_name: api
    build:
      context: ./api
      dockerfile: Dockerfile
    ports:
      - "5555:5000"
    depends_on:
      - mysql
    environment:
      DB_HOST: mysql
      DB_PORT: 3306
      DB_USER: root
      DB_PASSWORD: password
      DB_NAME: time_db
  
  frontend:
    restart: always
    container_name: frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "8954:8954"
    depends_on:
      - api
  
  mysql:
    restart: always
    container_name: mysql
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: time_db
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
  
  adminer:
    restart: always
    container_name: adminer
    image: adminer
    ports:
      - "8122:8080"
    depends_on:
      - mysql

volumes:
  mysql_data:
